### ISSUE TITLE
Username and password requested for install

### ISSUE THREAD

**Issue by andreszs** [bgta/net.bgta.phonegap.appversion#8]
When using the command `cordova plugin add https://github.com/rromerogar/net.bgta.phonegap.appversion.git`, as soon as the plugin is fetched I am prompted to type a `Username for https://github.com` and then a password. I couldn't find any username nor password in the readme, so please provide alternate instrucions or fix the install method, thanks.

**Comment by bgta** [comment]
@andreszs is your github username & password?
