### ISSUE TITLE
Uncaught ReferenceError: getAppVersion is not defined

### ISSUE THREAD

**Issue by cooldeeparmar** [bgta/net.bgta.phonegap.appversion#9]
Add this plugin line in config.xml 
<gap:plugin name="net.bgta.phonegap.plugins.appversion" version="1.0.0" />  

code in main js file 
getAppVersion(function(version) {
    console.log('Native App Version: ' + version);
});

app is not working please help me

**Comment by bgta** [comment]
have you installed the plugin in your project?

`cordova plugin add https://github.com/bgta/net.bgta.phonegap.appversion.git --save`

**Comment by cooldeeparmar** [comment]
yes i am installed  this plugin.  run my app  in phonegap mobile app.....it can not display the any content or error ..

**Comment by bgta** [comment]
@cooldeeparmar do you use getAppVersion under onDeviceReady event? If you try to use it before, the plugin is not loaded.
```
    document.addEventListener('deviceready', function onDeviceReady() {
        getAppVersion(function(version) {
            console.log('Native App Version: ' + version);
        });
    }, false);
```

**Comment by bgta** [comment]
See this example app: https://mega.nz/#!DtAF3ZQD

Works fine.

**Comment by cooldeeparmar** [comment]
![mega](https://cloud.githubusercontent.com/assets/12858833/18904109/1b02c4b8-857a-11e6-9ac3-b0a58b4c86f8.png)

what is a key ?

**Comment by bgta** [comment]
@cooldeeparmar sorry, try this link:
https://mega.nz/#!DtAF3ZQD!c53as4j2jlHMlnsEsPHJlHsMMO2utbLClhg1iYifJ5U

**Comment by cooldeeparmar** [comment]
@bgta Thanx......

**Comment by bgta** [comment]
@cooldeeparmar Thanks to you! 👍
